---
- name: install dotnet on ubuntu 22.04
  hosts: all
  become: yes
  tasks:
    - name: download
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb 
        dest: /home/ubuntu
    - name: package manager of debian
      ansible.builtin.apt:
        dpkg_options: -i packages-microsoft-prod.deb
        state: present
        name : apt
    - name: install dotnet
      ansible.builtin.apt:
        name: 
          - apt-transport-https 
          - dotnet-sdk-6.0
          - dotnet-runtime-6.0
        update_cache: true
        state: present
    
        
        
