---
- name: inastall httpd on redhat
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.yum:
        name: httpd
        state: present
        update_cache: true
      


   
