---
- name: install lamp
  hosts: all
  become: yes
  tasks:
    - name: install lampstack
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: present
    - name: install mysql
      ansible.builtin.apt:
        name: mysql-server
        state: present
    - name: install php
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: true
    - name: copy php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
    - name: system restart
      ansible.builtin.systemd:
        name: apache2
        state: restarted 
        
