
---
- name: Deploying SpringPetclinic
  hosts: all
  become: yes
  tasks:
    - name: check if playbook is being executed on supported os
      ansible.builtin.fail:
        msg: "This playbook is designed to run on ubuntu only"
      when: ansible_facts['distribution'] != "Ubuntu"
    - name: installing java-17 and maven
      ansible.builtin.apt:
        name:
        - openjdk-17-jdk
        - maven
        update_cache: yes
        state: present
    - name: Cloning springpetclinic
      ansible.builtin.git:
        repo: https://github.com/spring-projects/spring-petclinic.git
        dest: /home/c/spc
        update: false
    - name: Changing ownership of spc to adduser
      ansible.builtin.file:
        path: /home/c/spc/pom.xml
        owner: c
        group: c
        mode: u=rwx,g=rwx,o=rxw
    - name: find if the spc is already packaged
      ansible.builtin.stat:
        path: /home/c/spc/target/spring-petclinic-3.1.0-SNAPSHOT.jar
      register: spc 
    - name: Changing directory and mvn packaging
      ansible.builtin.command:
        chdir: spc
        cmd: mvn package -U -Dmaven.test.failure.ignore=true
      when: not spc.stat.exists
    - name: copy the service file
      ansible.builtin.copy:
        src: spring.service
        dest: /home/c/spring.service
   
   


      


   
   





