---
- name: install seacreates from awscli
  hosts: all
  become: yes
  tasks:
    - name: install awscli from ubuntu
      ansible.builtin.apt:
        name: awscli
        update_cache: true
        state: present
    - name: copy the iamuser credentials
      ansible.builtin.copy:
        src: r.sh
        dest: /home/r/r.sh
        