---
- name: install php
  hosts: u:wq!
  buntu
  become: yes
  tasks:
    - name: install apache2 
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: present
    - name: install php on ubuntu
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        update_cache: true
        state: present
      notify: 
        - restart apache2
      when: ansible_facts ['os_family'] == 'Ubuntu'
    - name: copy info.php file
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
      notify:
        - restart apache2
      when: ansible_facts['os_family'] == 'Ubuntu'
    - name: install apache on RHAT
      ansible.builtin.yum:
        name: httpd
        update_cache: true
        state: present
      when: ansible_facts ['os_family'] == 'RedHat'
    - name: start httpd server
      ansible.builtin.systemd: 
        name: httpd
        enabled: yes
        state: started
      when: ansible_facts ['os_family'] = 'RedHat'
    - name: install php on redhat
      ansible.builtin.yum:
        name: php
        update_cache: true
        state: present
      notify: 
        - restart apache
      when: ansible_facts ['os_family'] == 'RedHat'
    - name: copy info-php on redhat
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
      notify: 
        - restart apache
      when: ansible_facts['os_facts'] == 'RedHat'
  handlers:
    - name: restart apache2
      ansible.builtin.systemd:
        name: httpd
        state: restarted
    - name: restart apache 
      ansible.builtin.systemd:
        name: apache2
        state: restarted

  